name       : kded
version    : 5.74.0
release    : 40
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.74/kded-5.74.0.tar.xz : e6bf23e59afbd7d1f89082f748db1c0370413a40c99bdfc6f08a54fbd58471f1
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Central daemon of KDE work spaces
description: |
    KDED runs in the background and performs a number of small tasks. Some of these tasks are built in, others are started on demand.
patterns   :
    - /usr/lib64/libkdeinit*.so
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kinit-devel
    - kservice-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
