name       : kded
version    : 5.57.0
release    : 24
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.57/kded-5.57.0.tar.xz : 04327dda12fa547bebb8e1b1bc26373e8f4174007dd629231403d59ce004201f
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Central daemon of KDE work spaces
description: |
    KDED runs in the background and performs a number of small tasks. Some of these tasks are built in, others are started on demand.
patterns   :
    - /usr/lib64/libkdeinit*.so
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kinit-devel
    - kservice-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
