name       : kded
version    : 5.43.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.43/kded-5.43.0.tar.xz : 79e0ce49fb6760cf9985523968b6229e9cd187a56f963321508975489c88d4cd
license    :
    - LGPL-2.0
    - LGPL-2.1
component  : programming
optimize   : lto
summary    : Central daemon of KDE work spaces
description: |
    KDED runs in the background and performs a number of small tasks. Some of these tasks are built in, others are started on demand.
patterns   :
    - /usr/lib64/libkdeinit*.so
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kinit-devel
    - kservice-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
