name       : kded
version    : 5.49.0
release    : 16
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.49/kded-5.49.0.tar.xz : cc7f716e2086f44410aa13b8415aad1dcf9ce1c8c78ec7250a66e875f5d0d0d0
license    :
    - LGPL-2.0
    - LGPL-2.1
component  : programming
optimize   : lto
summary    : Central daemon of KDE work spaces
description: |
    KDED runs in the background and performs a number of small tasks. Some of these tasks are built in, others are started on demand.
patterns   :
    - /usr/lib64/libkdeinit*.so
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kinit-devel
    - kservice-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
