name       : kded
version    : 5.85.0
release    : 52
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.85/kded-5.85.0.tar.xz : 3c361952918e4f887a7db0ab202525488871ad8e4ea33715040ce89cd94f59f9
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.0-or-later
component  : programming.library
summary    : Central daemon of KDE work spaces
description: |
    KDED runs in the background and performs a number of small tasks. Some of these tasks are built in, others are started on demand.
patterns   :
    - /usr/lib64/libkdeinit*.so
optimize   : lto
builddeps  :
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kservice-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
