name       : kded
version    : 5.105.0
release    : 66
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.105/kded-5.105.0.tar.xz : ac588d6ee850ce60b5128043617c6986cd04122e792052b1d515c4343ed851fb
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.0-or-later
component  : programming.library
summary    : Central daemon of KDE work spaces
description: |
    KDED runs in the background and performs a number of small tasks. Some of these tasks are built in, others are started on demand.
patterns   :
    - /usr/lib64/libkdeinit*.so
optimize   : lto
builddeps  :
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kservice-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
