name       : kded
version    : 5.83.0
release    : 50
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.83/kded-5.83.0.tar.xz : 69319e6bc587c1089ee46fc8933484790a816355909df2830721b25911a09b3b
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.0-or-later
component  : programming.library
summary    : Central daemon of KDE work spaces
description: |
    KDED runs in the background and performs a number of small tasks. Some of these tasks are built in, others are started on demand.
patterns   :
    - /usr/lib64/libkdeinit*.so
optimize   : lto
builddeps  :
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kservice-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
