name       : kded
version    : 5.63.0
release    : 30
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.63/kded-5.63.0.tar.xz : 055087306a3c7c970a13f8ba3fddaba433cc68fc67a5a88b56be9b179c33594e
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Central daemon of KDE work spaces
description: |
    KDED runs in the background and performs a number of small tasks. Some of these tasks are built in, others are started on demand.
patterns   :
    - /usr/lib64/libkdeinit*.so
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kinit-devel
    - kservice-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
