name       : kded
version    : 5.54.0
release    : 21
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.54/kded-5.54.0.tar.xz : f6e16c19d073dfc0a908bddead6337debbe3bf9429c8b09c0ed0cf8d6fdf308c
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Central daemon of KDE work spaces
description: |
    KDED runs in the background and performs a number of small tasks. Some of these tasks are built in, others are started on demand.
patterns   :
    - /usr/lib64/libkdeinit*.so
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kinit-devel
    - kservice-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
