name       : kded
version    : 5.39.0
release    : 6
source     :
    - https://download.kde.org/stable/frameworks/5.39/kded-5.39.0.tar.xz : 453d349874b71a500afbb4a7c576be77bf38d3e87bd818269ccdfd27287c644b
license    :
    - LGPL-2.0
    - LGPL-2.1
component  : programming
summary    : Central daemon of KDE work spaces
description: |
    KDED runs in the background and performs a number of small tasks. Some of these tasks are built in, others are started on demand.
patterns   :
    - /usr/lib64/libkdeinit*.so
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kinit-devel
    - kservice-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
