name       : kded
version    : 5.32.0
release    : 2
source     :
    - http://download.kde.org/stable/frameworks/5.32/kded-5.32.0.tar.xz : 064359f27e0c98ba28425a4a5827a800bd3dc2a32626d7fbf606f1c9f1d6b55e
license    :
    - LGPL-2.0
    - LGPL-2.1
component  : programming
summary    : Central daemon of KDE work spaces
description: |
    KDED runs in the background and performs a number of small tasks. Some of these tasks are built in, others are started on demand.
patterns   :
    - /usr/lib64/libkdeinit*.so
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kinit-devel
    - kservice-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
