name       : kded
version    : 5.87.0
release    : 53
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.87/kded-5.87.0.tar.xz : 256bcaee8101bd3c9ec239bc3853fd8f7d5a98383858e509809a572a5a0bbca1
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.0-or-later
component  : programming.library
summary    : Central daemon of KDE work spaces
description: |
    KDED runs in the background and performs a number of small tasks. Some of these tasks are built in, others are started on demand.
patterns   :
    - /usr/lib64/libkdeinit*.so
optimize   : lto
builddeps  :
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kservice-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
