name       : kded
version    : 5.44.0
release    : 11
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.44/kded-5.44.0.tar.xz : 5a25e7a26d7d0cd67fbd105a4589a173d0c964e4b80e4d0530cef1eccad74d13
license    :
    - LGPL-2.0
    - LGPL-2.1
component  : programming
optimize   : lto
summary    : Central daemon of KDE work spaces
description: |
    KDED runs in the background and performs a number of small tasks. Some of these tasks are built in, others are started on demand.
patterns   :
    - /usr/lib64/libkdeinit*.so
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kinit-devel
    - kservice-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
