name       : kded
version    : 5.64.0
release    : 31
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.64/kded-5.64.0.tar.xz : 2e8bda93918ac174254c8f70a71c9d6966a4721e14a631760e1b912d108001be
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Central daemon of KDE work spaces
description: |
    KDED runs in the background and performs a number of small tasks. Some of these tasks are built in, others are started on demand.
patterns   :
    - /usr/lib64/libkdeinit*.so
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kinit-devel
    - kservice-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
