name       : kded
version    : 5.92.0
release    : 58
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.92/kded-5.92.0.tar.xz : 8335531b856cb361ab2e5b390b333eb3405bac4e2bc7c0305994704bd0540e6c
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.0-or-later
component  : programming.library
summary    : Central daemon of KDE work spaces
description: |
    KDED runs in the background and performs a number of small tasks. Some of these tasks are built in, others are started on demand.
patterns   :
    - /usr/lib64/libkdeinit*.so
optimize   : lto
builddeps  :
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kservice-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
