name       : kded
version    : 5.59.0
release    : 26
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.59/kded-5.59.0.tar.xz : 88e1f19674da8c40b3e97ab5cfcb2252143b3a36de55bd45959694c1e623af9c
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Central daemon of KDE work spaces
description: |
    KDED runs in the background and performs a number of small tasks. Some of these tasks are built in, others are started on demand.
patterns   :
    - /usr/lib64/libkdeinit*.so
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kinit-devel
    - kservice-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
